
import java.awt.Color;
import java.awt.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alexpieprzycki
 */
public class GameView extends javax.swing.JPanel {
    
    /**
     * Creates new form GameView
     */
    public GameView() {
        initComponents();
    }

    public void paintComponent(Graphics g){
        super.paintComponent(g);
         Pattern rect = new Rectangle(1, 1, 6, 6);
        
        //System.out.println(rect.toString());
        Battleship battle = new Battleship(6, 7, rect, 3, 6);
        //Battleship battle2 = new Battleship()
        int[][] gameBoard = new int[30][30];
        Battleship[] array = new Battleship[1];
        array[0] = battle;
        GameBoard game1 = new GameBoard(array);
        g.setColor(Color.BLACK);
        g.drawRect(0,0,50,50);
        game1.drawBoard(g);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
