
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alexpieprzycki
 */
public class GameView extends javax.swing.JPanel {
    
    private static ArrayList<Battleship> list;
    private GameBoard game1;
    private static JFrame frame;
    /**
     * Creates new form GameView
     */
    public GameView(ArrayList<Battleship> battle) {
        list = battle;
        initComponents();
    }
    
    public void addShip(Battleship battle){
        list.add(battle);
        repaint();
    }
    
    public void update(){
        repaint();
       
    }

    public void paintComponent(Graphics g){
        super.paintComponent(g);
//         Pattern rect = new Rectangle(1, 1, 6, 6);
//        
//        //System.out.println(rect.toString());
//        Battleship battle = new Battleship(3, 1, rect, 1, 1);
//        //Battleship battle2 = new Battleship()
//        int[][] gameBoard = new int[30][30];
//        list.add(battle);
        game1 = new GameBoard(list);
        game1.drawBoard(g);
        
    }
    
    public static void main(String[] args) {
        frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);       
        frame.getContentPane().add(new GameView(list));
        frame.pack();
        frame.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
