
import java.awt.Color;
import java.awt.Graphics;
import java.util.*;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author maorgozalzani
 * Makes the setup window frame
 */
public class SetUp extends javax.swing.JFrame {

    private String speed, size, row, col, patternW, patternL;
    private ArrayList<Rectangle> rArray = new ArrayList<>();
    private ArrayList<Battleship> bArray = new ArrayList<>();
    private GameBoard game1;

    /**
     * Creates new form SetUp
     */
    public SetUp() {
        initComponents();
        errorLabel.setVisible(false);
        progressBar.setVisible(false);
        addedLabel.setVisible(false);
        doneButton.setVisible(false);


    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        boardPanel = boardPanel= new GameView(bArray);
        setUpPanel = new javax.swing.JPanel();
        SizeLabel = new javax.swing.JLabel();
        SpeedLabel = new javax.swing.JLabel();
        SpeedText = new javax.swing.JTextField();
        SizeText = new javax.swing.JTextField();
        progressBar = new javax.swing.JProgressBar();
        bRow = new javax.swing.JLabel();
        RowText = new javax.swing.JTextField();
        bColLabel = new javax.swing.JLabel();
        ColText = new javax.swing.JTextField();
        PWidthLabel = new javax.swing.JLabel();
        PWidthText = new javax.swing.JTextField();
        PLengthLabel = new javax.swing.JLabel();
        PLengthText = new javax.swing.JTextField();
        AddShipButton = new javax.swing.JButton();
        newShip = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        addedLabel = new javax.swing.JLabel();
        doneButton = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout boardPanelLayout = new javax.swing.GroupLayout(boardPanel);
        boardPanel.setLayout(boardPanelLayout);
        boardPanelLayout.setHorizontalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        boardPanelLayout.setVerticalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );

        SizeLabel.setText("Enter Size:");

        SpeedLabel.setText("Enter Speed");

        SpeedText.setColumns(3);
        SpeedText.setText("          ");
        SpeedText.setToolTipText("Enter Speed");

        SizeText.setColumns(3);
        SizeText.setText("          ");
        SizeText.setToolTipText("Greater than 0");

        progressBar.setForeground(new java.awt.Color(0, 250, 0));

        bRow.setText("Enter Ship's Row:");

        RowText.setColumns(3);
        RowText.setText("          ");
        RowText.setToolTipText("Enter Row");

        bColLabel.setText("Enter Ship's Col:");

        ColText.setColumns(3);
        ColText.setText("          ");
        ColText.setToolTipText("Enter Column");

        PWidthLabel.setText("Enter Pattern's Width:");

        PWidthText.setColumns(3);
        PWidthText.setText("          ");
        PWidthText.setToolTipText("Can't be <= size");

        PLengthLabel.setText("Enter Pattern's length:");

        PLengthText.setColumns(3);
        PLengthText.setText("          ");
        PLengthText.setToolTipText("Can't be <= size");

        AddShipButton.setBackground(new java.awt.Color(255, 255, 255));
        AddShipButton.setText("Add Ship");
        AddShipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddShipButtonActionPerformed(evt);
            }
        });

        newShip.setText("Make a New Ship");
        newShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newShipActionPerformed(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(250, 0, 0));
        errorLabel.setText("\"Please enter valid values      ");

        addedLabel.setBackground(new java.awt.Color(0, 255, 0));
        addedLabel.setText("Ship Added!");
        addedLabel.setToolTipText("");

        doneButton.setBackground(new java.awt.Color(0, 240, 0));
        doneButton.setText("Done!");
        doneButton.setToolTipText("Only Click When Done With Setup");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout setUpPanelLayout = new javax.swing.GroupLayout(setUpPanel);
        setUpPanel.setLayout(setUpPanelLayout);
        setUpPanelLayout.setHorizontalGroup(
            setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setUpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setUpPanelLayout.createSequentialGroup()
                        .addComponent(PWidthLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PWidthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(setUpPanelLayout.createSequentialGroup()
                        .addComponent(PLengthLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PLengthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setUpPanelLayout.createSequentialGroup()
                        .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SizeLabel)
                            .addComponent(SpeedLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpeedText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))))
            .addGroup(setUpPanelLayout.createSequentialGroup()
                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setUpPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bRow)
                            .addComponent(bColLabel))
                        .addGap(18, 18, 18)
                        .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ColText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RowText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(setUpPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(newShip))
                    .addGroup(setUpPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setUpPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(errorLabel)
                .addGap(16, 16, 16))
            .addGroup(setUpPanelLayout.createSequentialGroup()
                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setUpPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(AddShipButton))
                    .addGroup(setUpPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(addedLabel))
                    .addGroup(setUpPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(doneButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        setUpPanelLayout.setVerticalGroup(
            setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setUpPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(newShip)
                .addGap(18, 18, 18)
                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SizeLabel)
                    .addComponent(SizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpeedLabel)
                    .addComponent(SpeedText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bRow)
                    .addComponent(RowText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bColLabel)
                    .addComponent(ColText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PWidthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PWidthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PLengthLabel)
                    .addComponent(PLengthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddShipButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(doneButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(setUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(setUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddShipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddShipButtonActionPerformed
        // TODO add your handling code here:
        speed = SpeedText.getText();
        size = SizeText.getText();
        row = RowText.getText();
        col = ColText.getText();
        patternW = PWidthText.getText();
        patternL = PLengthText.getText();

        int speed = Integer.parseInt(this.speed);
        int size = Integer.parseInt(this.size);
        int row = Integer.parseInt(this.row);
        int col = Integer.parseInt(this.col);
        int pW = Integer.parseInt(patternW);
        int pL = Integer.parseInt(patternL);
        if (size >= pW || size >= pL || size <= 0) {
            errorLabel.setVisible(true);
            AddShipButton.setBackground(Color.red);
        } else {
            AddShipButton.setBackground(Color.GREEN);
            errorLabel.setVisible(false);
            rArray.add(new Rectangle(row, col, pW, pL));
            bArray.add(new Battleship(size, speed, rArray.get(rArray.size()-1), row, col));
            addedLabel.setVisible(true);
            
           // Graphics g = null;
           // boardPanel.update(g);
        }
    }//GEN-LAST:event_AddShipButtonActionPerformed

    public  ArrayList<Battleship> getList(){
        return bArray;
    }
    
    private void newShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newShipActionPerformed
        // TODO add your handling code here:
        SizeText.setText("");
        SpeedText.setText("");
        RowText.setText("");
        ColText.setText("");
        PWidthText.setText("");
        PLengthText.setText("");
        errorLabel.setVisible(false);
        addedLabel.setVisible(true);
        AddShipButton.setBackground(Color.WHITE);
       // boardPanel.addShip(bArray.get(bArray.size()-1));
    }//GEN-LAST:event_newShipActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
        ComputerPlayer cPlayer= new ComputerPlayer(game1);

        JFrame playFrame= new GamePlay(bArray, cPlayer.getList());
        
    }//GEN-LAST:event_doneButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SetUp().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddShipButton;
    private javax.swing.JTextField ColText;
    private javax.swing.JLabel PLengthLabel;
    private javax.swing.JTextField PLengthText;
    private javax.swing.JLabel PWidthLabel;
    private javax.swing.JTextField PWidthText;
    private javax.swing.JTextField RowText;
    private javax.swing.JLabel SizeLabel;
    private javax.swing.JTextField SizeText;
    private javax.swing.JLabel SpeedLabel;
    private javax.swing.JTextField SpeedText;
    private javax.swing.JLabel addedLabel;
    private javax.swing.JLabel bColLabel;
    private javax.swing.JLabel bRow;
    private javax.swing.JPanel boardPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton newShip;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JPanel setUpPanel;
    // End of variables declaration//GEN-END:variables
}
